# Generated by Django 3.0.3 on 2020-02-20 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("elections", "0003_auto_20200220_0508")]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="participant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="candidates",
                to="elections.Participant",
            ),
        )
    ]
