# Generated by Django 3.0.3 on 2020-03-03 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("elections", "0006_auto_20200225_0523")]

    operations = [
        migrations.RenameField(
            model_name="election", old_name="description", new_name="title"
        ),
        migrations.AlterField(
            model_name="vote",
            name="candidate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="votes",
                to="elections.Candidate",
            ),
        ),
    ]
