version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.4
        environment:
          PYTHONPATH: .
          SECRET_KEY: test_secret_key
          DJANGO_SETTINGS_MODULE: whichflix.settings.local
          DATABASE_URL: postgres://root:password@localhost/circle_test?sslmode=disable
          TMDB_API_KEY: test_tmdb_api_key
          REDIS_URL: redis://:@127.0.0.1:6379
          FANOUT_REALM_KEY: dGVzdA==
      - image: circleci/postgres:9.6
        environment:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: password
          POSTGRES_DB: circle_test
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo pip install -r requirements.txt
      - run:
          name: Run tests
          command: |
            coverage run --source='.' ./whichflix/manage.py test
      - run:
          name: Generate coverage report
          command: |
            coverage json
      - codecov/upload:
          token: dff4c637-8a57-42a8-a267-b774193e3a47
          file: ./coverage.json
      - store_artifacts:
          path: ./coverage.json
