# Generated by Django 3.0.3 on 2020-02-13 05:44

from typing import List, Tuple
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies: List[Tuple] = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider_slug",
                    models.CharField(
                        choices=[("the_movie_database", "The Movie Database")],
                        max_length=255,
                    ),
                ),
                ("provider_id", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "unique_together": {("provider_id", "provider_slug")},
                "index_together": {("provider_id", "provider_slug")},
            },
        )
    ]
