# Generated by Django 3.0.3 on 2020-02-20 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("elections", "0002_auto_20200220_0447")]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="election",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="participants",
                to="elections.Election",
            ),
        )
    ]
