# Generated by Django 3.0.3 on 2020-02-25 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
        ("users", "0002_device"),
        ("elections", "0005_candidate_election"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="candidate", unique_together={("participant", "election", "movie")}
        ),
        migrations.AlterUniqueTogether(
            name="participant", unique_together={("device", "election")}
        ),
        migrations.AlterUniqueTogether(
            name="vote", unique_together={("participant", "candidate")}
        ),
    ]
