# Generated by Django 3.0.3 on 2020-03-29 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("elections", "0007_auto_20200303_0154")]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        )
    ]
