# Generated by Django 3.0.4 on 2020-04-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("elections", "0008_participant_deleted_at")]

    operations = [
        migrations.AddField(
            model_name="vote",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        )
    ]
