# Generated by Django 3.0.5 on 2020-05-20 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("elections", "0009_vote_deleted_at")]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="movie_id_temp",
            field=models.CharField(default=603, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="candidate",
            unique_together={("participant", "election", "movie_id_temp")},
        ),
        migrations.RemoveField(model_name="candidate", name="movie"),
    ]
