# Generated by Django 3.0.5 on 2020-05-20 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("elections", "0010_auto_20200520_2047")]

    operations = [
        migrations.RenameField(
            model_name="candidate", old_name="movie_id_temp", new_name="movie_id"
        ),
        migrations.AlterUniqueTogether(
            name="candidate", unique_together={("participant", "election", "movie_id")}
        ),
    ]
